### ISSUE TITLE
Unexpected token * || /tupelo-wasm-sdk/examples/set-and-get-data/node_modules/interface-datastore/src/utils.js:8

### ISSUE THREAD

**Issue by ommzi91** [quorumcontrol/tupelo-wasm-sdk#89]
/tupelo-wasm-sdk/examples/set-and-get-data/node_modules/interface-datastore/src/utils.js:8
  return (async function * () {
                         ^

SyntaxError: Unexpected token *

**Comment by tobowers** [comment]
Hi @ommzi91. Thanks for reporting? Could you explain how you got that error? We run each example on every push and the tests have been passing: https://github.com/quorumcontrol/tupelo-wasm-sdk/runs/503473428?check_suite_focus=true

What version of node are you on?

**Comment by ommzi91** [comment]
I am using v8.10.0 o node

I got error by following steps on https://github.com/quorumcontrol/tupelo-wasm-sdk/tree/master/examples/set-and-get-data

**Comment by tobowers** [comment]
@ommzi91 that's a pretty old version of node. Can you try on v12.1.0?

**Comment by ommzi91** [comment]
Ok thanks @tobowers  I will try
